function general_data(patdat)

idx_group = ...                                                             % super bulky way to extract the indices for both groups
    cellfun(@(c)strcmp(c,cellstr(table2array(patdat(:,3)))), ...
    {'1','2'},'Un',0);
idx_subtype = unique(table2array(patdat(:,6)));
if any(isnan(idx_subtype))
    idx_subtype(isnan(idx_subtype)) = [];
end
typs = {'HR', 'TD', 'MX'};

for g = 1:size(idx_group,2)
    n{g} = sprintf('%s', ...
        num2str(nansum(idx_group{g}))); %#ok<*AGROW,*NASGU>
    age{g} = ...
        sprintf('%.02f ± %.02f yrs.', ...
        nanmean(table2array(patdat(idx_group{g},4))), ...
        nanstd(table2array(patdat(idx_group{g},4))));% extracts the age of both groups
    height{g} = ...
        sprintf('%.02f ± %.02f m.', ...
        1/100*nanmean(table2array(patdat(idx_group{g},7))), ...
        1/100*nanstd(table2array(patdat(idx_group{g},7))));% extracts the age of both groups
    
    idx_gdr = ...                                                             % super bulky way to extract the indices for both groups
        cell2mat(cellfun(@(c)strcmp(c,cellstr(table2array(patdat(idx_group{g},5)))),{'0'},'Un',0));
    gndr{g} = ...
        sprintf('%s ? : %s ?', ...
        num2str(nansum(idx_gdr)), ...
        num2str(nansum(idx_group{g}) - nansum(idx_gdr)));% extracts the age of both groups
    
end
T = array2table([{n{1}, gndr{1}, age{1}, height{1}}; ...
    {n{2}, gndr{2}, age{2}, height{2}}].', ...
    'VariableNames', {'PD', 'CTRL'}, 'RowNames', {'n', 'gender', 'age', 'height'});
T

%% Subtype specific table
for g = 1:numel(idx_subtype)+1
    if g <= numel(idx_subtype)
        idx_temp = find(table2array(patdat(:,6))==g-1 & idx_group{1}==1);
    else
        idx_temp = find(~isnan(table2array(patdat(:,6))) & idx_group{1}==1);
    end
    
    n{g} = sprintf('%s', ...
        num2str(numel(idx_temp))); %#ok<*AGROW,*NASGU>
    age{g} = ...
        sprintf('%.02f ± %.02f yrs.', ...
        nanmean(table2array(patdat(idx_temp,4))), ...
        nanstd(table2array(patdat(idx_temp,4))));% extracts the age of both groups
    height{g} = ...
        sprintf('%.02f ± %.02f m.', ...
        1/100*nanmean(table2array(patdat(idx_temp,7))), ...
        1/100*nanstd(table2array(patdat(idx_temp,7))));
    
    idx_gdr = ...                                                             % super bulky way to extract the indices for both groups
        cell2mat(cellfun(@(c)strcmp(c,cellstr(table2array(patdat(idx_temp,5)))),{'0'},'Un',0));
    gndr{g} = ...
        sprintf('%s ? : %s ?', ...
        num2str(nansum(idx_gdr)), ...
        num2str(numel(idx_temp) - nansum(idx_gdr)));
    
    H_Y{g} = ...
        sprintf('%.01f ± %.01f', ...
        nanmean(table2array(patdat(idx_temp,9))), ...
        nanstd(table2array(patdat(idx_temp,9))));
    
    ledd{g} = ...
        sprintf('%.02f mg ± %.02f mg', ...
        nanmean(table2array(patdat(idx_temp,16))), ...
        nanstd(table2array(patdat(idx_temp,16))));
    
    dd{g} = ...
        sprintf('%.01f yrs. ± %.01f yrs', ...
        nanmean(table2array(patdat(idx_temp,8))), ...
        nanstd(table2array(patdat(idx_temp,8))));% extracts the age of both groups
    
    updrs_off{g} = ...
        sprintf('%.02f ± %.02f ', ...
        nanmean(table2array(patdat(idx_temp,10))), ...
        nanstd(table2array(patdat(idx_temp,10))));
    
    updrs_on{g} = ...
        sprintf('%.02f ± %.02f ', ...
        nanmean(table2array(patdat(idx_temp,11))), ...
        nanstd(table2array(patdat(idx_temp,11))));
    
    updrs_diff{g} = ...
        sprintf('%.02f ± %.02f ', ...
        nanmean(table2array(patdat(idx_temp,12))), ...
        nanstd(table2array(patdat(idx_temp,12))));
end
%%
T = array2table([{n{1}, gndr{1}, age{1}, ledd{1}, H_Y{1}, dd{1}, updrs_off{1}, updrs_on{1}, updrs_diff{1}}; ...
    {n{2}, gndr{2}, age{2}, ledd{2}, H_Y{2}, dd{2},updrs_off{2}, updrs_on{2}, updrs_diff{2}}; ...
    {n{3}, gndr{3}, age{3}, ledd{3}, H_Y{3}, dd{3},updrs_off{3}, updrs_on{3}, updrs_diff{3}};...
    {n{4}, gndr{4}, age{4}, ledd{4}, H_Y{4}, dd{4},updrs_off{4}, updrs_on{4}, updrs_diff{4}}].', ...
    'VariableNames', {'HR', 'TD', 'MX', 'all'}, 'RowNames', {'n', 'gender', 'age', 'ledd', 'H&Y', 'DD', 'UPDRS_OFF', 'UPDRS_ON', 'UPDRS_DIFF'});
T